---
- hosts: master
  gather_facts: yes
  become: yes

  tasks:
    - name: Update repositories
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install git
      apt:
        name: git
        state: present
